// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NavbarModuleCssNamespace {
  export interface INavbarModuleCss {
    icon: string;
    logo: string;
    logout: string;
    navbar: string;
    search: string;
    themeIcon: string;
    user: string;
  }
}

declare const NavbarModuleCssModule: NavbarModuleCssNamespace.INavbarModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NavbarModuleCssNamespace.INavbarModuleCss;
};

export = NavbarModuleCssModule;
