// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LoginFormModuleCssNamespace {
  export interface ILoginFormModuleCss {
    button: string;
    error: string;
    form: string;
    input: string;
    inputError: string;
    loading: string;
    registrationButton: string;
  }
}

declare const LoginFormModuleCssModule: LoginFormModuleCssNamespace.ILoginFormModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LoginFormModuleCssNamespace.ILoginFormModuleCss;
};

export = LoginFormModuleCssModule;
