// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MessagesContainerModuleCssNamespace {
  export interface IMessagesContainerModuleCss {
    messagesContainer: string;
  }
}

declare const MessagesContainerModuleCssModule: MessagesContainerModuleCssNamespace.IMessagesContainerModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessagesContainerModuleCssNamespace.IMessagesContainerModuleCss;
};

export = MessagesContainerModuleCssModule;
