// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ChatsPageModuleCssNamespace {
  export interface IChatsPageModuleCss {
    container: string;
    divider: string;
    icon: string;
    search: string;
  }
}

declare const ChatsPageModuleCssModule: ChatsPageModuleCssNamespace.IChatsPageModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChatsPageModuleCssNamespace.IChatsPageModuleCss;
};

export = ChatsPageModuleCssModule;
