// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace GlobalUsersModuleCssNamespace {
  export interface IGlobalUsersModuleCss {
    container: string;
    list: string;
  }
}

declare const GlobalUsersModuleCssModule: GlobalUsersModuleCssNamespace.IGlobalUsersModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlobalUsersModuleCssNamespace.IGlobalUsersModuleCss;
};

export = GlobalUsersModuleCssModule;
