// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace UserRowModuleCssNamespace {
  export interface IUserRowModuleCss {
    addContact: string;
    avatar: string;
    container: string;
    controllers: string;
    main: string;
  }
}

declare const UserRowModuleCssModule: UserRowModuleCssNamespace.IUserRowModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: UserRowModuleCssNamespace.IUserRowModuleCss;
};

export = UserRowModuleCssModule;
