// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace UserModuleScssNamespace {
  export interface IUserModuleScss {
    avatar: string;
    name: string;
    user: string;
  }
}

declare const UserModuleScssModule: UserModuleScssNamespace.IUserModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: UserModuleScssNamespace.IUserModuleScss;
};

export = UserModuleScssModule;
