// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MessageLayoutModuleCssNamespace {
  export interface IMessageLayoutModuleCss {
    container: string;
    content: string;
    media: string;
    time: string;
  }
}

declare const MessageLayoutModuleCssModule: MessageLayoutModuleCssNamespace.IMessageLayoutModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessageLayoutModuleCssNamespace.IMessageLayoutModuleCss;
};

export = MessageLayoutModuleCssModule;
