// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MessageModuleCssNamespace {
  export interface IMessageModuleCss {
    message: string;
    messageAvatar: string;
    messageLayout: string;
    messageTextLarge: string;
    messageUsername: string;
    self: string;
  }
}

declare const MessageModuleCssModule: MessageModuleCssNamespace.IMessageModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessageModuleCssNamespace.IMessageModuleCss;
};

export = MessageModuleCssModule;
