// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PostModuleScssNamespace {
  export interface IPostModuleScss {
    container: string;
    content: string;
    date: string;
    details: string;
    info: string;
    item: string;
    namespan: string;
    post: string;
    themeDark: string;
    themeLight: string;
    user: string;
    userInfo: string;
  }
}

declare const PostModuleScssModule: PostModuleScssNamespace.IPostModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PostModuleScssNamespace.IPostModuleScss;
};

export = PostModuleScssModule;
