// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MessagesSkeletonModuleCssNamespace {
  export interface IMessagesSkeletonModuleCss {
    loading: string;
    message: string;
    messageAvatar: string;
    messageTextLarge: string;
    messageTextSmall: string;
    wrapper: string;
  }
}

declare const MessagesSkeletonModuleCssModule: MessagesSkeletonModuleCssNamespace.IMessagesSkeletonModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MessagesSkeletonModuleCssNamespace.IMessagesSkeletonModuleCss;
};

export = MessagesSkeletonModuleCssModule;
