// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleCssNamespace {
  export interface IIndexModuleCss {
    form: string;
    formSection: string;
    item: string;
    submit: string;
  }
}

declare const IndexModuleCssModule: IndexModuleCssNamespace.IIndexModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexModuleCssNamespace.IIndexModuleCss;
};

export = IndexModuleCssModule;
