// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContactsModuleCssNamespace {
  export interface IContactsModuleCss {
    container: string;
  }
}

declare const ContactsModuleCssModule: ContactsModuleCssNamespace.IContactsModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContactsModuleCssNamespace.IContactsModuleCss;
};

export = ContactsModuleCssModule;
