// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContactModuleCssNamespace {
  export interface IContactModuleCss {
    avatar: string;
    container: string;
    controllers: string;
    main: string;
  }
}

declare const ContactModuleCssModule: ContactModuleCssNamespace.IContactModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContactModuleCssNamespace.IContactModuleCss;
};

export = ContactModuleCssModule;
