// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContactsSearchModuleCssNamespace {
  export interface IContactsSearchModuleCss {
    container: string;
    icon: string;
    search: string;
  }
}

declare const ContactsSearchModuleCssModule: ContactsSearchModuleCssNamespace.IContactsSearchModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContactsSearchModuleCssNamespace.IContactsSearchModuleCss;
};

export = ContactsSearchModuleCssModule;
