// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LayoutModuleCssNamespace {
  export interface ILayoutModuleCss {
    main: string;
  }
}

declare const LayoutModuleCssModule: LayoutModuleCssNamespace.ILayoutModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LayoutModuleCssNamespace.ILayoutModuleCss;
};

export = LayoutModuleCssModule;
