// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ChatModuleCssNamespace {
  export interface IChatModuleCss {
    avatar: string;
    chatInfo: string;
    conf: string;
    container: string;
    date: string;
    lastMessage: string;
    li: string;
    link: string;
    text: string;
    user: string;
    userInfo: string;
  }
}

declare const ChatModuleCssModule: ChatModuleCssNamespace.IChatModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChatModuleCssNamespace.IChatModuleCss;
};

export = ChatModuleCssModule;
