// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProfileModuleCssNamespace {
  export interface IProfileModuleCss {
    avatar: string;
    avatarContainer: string;
    cover: string;
    coverContainer: string;
    editButton: string;
    profileContainer: string;
    userCard: string;
    userInfo: string;
    userInfoItem: string;
    userInfoList: string;
  }
}

declare const ProfileModuleCssModule: ProfileModuleCssNamespace.IProfileModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProfileModuleCssNamespace.IProfileModuleCss;
};

export = ProfileModuleCssModule;
