// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RegistrationFormModuleCssNamespace {
  export interface IRegistrationFormModuleCss {
    button: string;
    error: string;
    form: string;
    input: string;
    inputError: string;
    loading: string;
    loginButton: string;
  }
}

declare const RegistrationFormModuleCssModule: RegistrationFormModuleCssNamespace.IRegistrationFormModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RegistrationFormModuleCssNamespace.IRegistrationFormModuleCss;
};

export = RegistrationFormModuleCssModule;
