// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ChatHeaderModuleCssNamespace {
  export interface IChatHeaderModuleCss {
    back: string;
    control: string;
    controls: string;
    header: string;
    info: string;
    lastOnline: string;
    name: string;
    userAvatar: string;
  }
}

declare const ChatHeaderModuleCssModule: ChatHeaderModuleCssNamespace.IChatHeaderModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ChatHeaderModuleCssNamespace.IChatHeaderModuleCss;
};

export = ChatHeaderModuleCssModule;
