// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleCssNamespace {
  export interface IIndexModuleCss {
    avatar: string;
    avatarContainer: string;
    avatarControls: string;
    avatarWrapper: string;
    cover: string;
    coverContainer: string;
    coverControls: string;
    editCover: string;
    header: string;
    input: string;
    profileContainer: string;
    userCard: string;
    userInfo: string;
  }
}

declare const IndexModuleCssModule: IndexModuleCssNamespace.IIndexModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexModuleCssNamespace.IIndexModuleCss;
};

export = IndexModuleCssModule;
