// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace UserModuleCssNamespace {
  export interface IUserModuleCss {
    avatar: string;
    avatarlink: string;
    link: string;
    user: string;
    username: string;
  }
}

declare const UserModuleCssModule: UserModuleCssNamespace.IUserModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: UserModuleCssNamespace.IUserModuleCss;
};

export = UserModuleCssModule;
