// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RegistrationModuleCssNamespace {
  export interface IRegistrationModuleCss {
    card: string;
    left: string;
    registration: string;
  }
}

declare const RegistrationModuleCssModule: RegistrationModuleCssNamespace.IRegistrationModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RegistrationModuleCssNamespace.IRegistrationModuleCss;
};

export = RegistrationModuleCssModule;
